import Tour from "../TouristAttractionsPage/Tour";

const Trips = [
    {
        id: 1,
        OraganizationId: 1,
        Origin: { country: "Egypt", city: "Cairo" },
        Destinations: [
            { country: "Egypt", city: "Alexandria" },
            { country: "Egypt", city: "Aswan" },
        ],
        DepartureTransportation: "Bus",
        ReturnTransportation: "Air Plane",
        DepartureDate: "2023-06-01 16:00",
        ReturnDate: "2023-06-05 16:00",
        Description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae tincidunt ultricies, nunc nisl ultricies nunc, vitae ultricies n",
        Price: 1000,
        Capacity: 50,
        Image: "https://www.egypttoursportal.com/wp-content/uploads/2018/05/cairo-and-nile-cruise-holidays.jpg",
        TourLeaderIds: [1, 2, 3],
        PlaceIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    },
    {
        id: 2,
        OraganizationId: 2,
        Origin: { country: "France", city: "Paris" },
        Destinations: [
            { country: "Germany", city: "Berlin" },
            { country: "Italy", city: "Rome" },
            { country: "Spain", city: "Madrid" },
            { country: "England", city: "London" },
        ],
        DepartureTransportation: "Air Plane",
        ReturnTransportation: "Air Plane",
        DepartureDate: "2023-06-03 22:00",
        ReturnDate: "2023-06-10 08:00",
        Description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae tincidunt ultricies, nunc nisl ultricies nunc, vitae ultricies n",
        Price: 2000,
        Capacity: 50,
        Image: "https://cdn.britannica.com/39/6839-050-27891400/Brandenburg-Gate-Berlin.jpg?w=300",
        TourLeaderIds: [4, 5, 6],
        PlaceIds: [11, 12, 13, 14, 15],
    },
    {
        id: 3,
        OraganizationId: 1,
        Origin: { country: "United States", city: "New York" },
        Destinations: [
            { country: "Canada", city: "Toronto" },
            { country: "Mexico", city: "Mexico City" },
            { country: "Brazil", city: "Rio de Janeiro" },
            { country: "Argentina", city: "Buenos Aires" },
        ],
        DepartureTransportation: "Train",
        ReturnTransportation: "Train",
        DepartureDate: "2023-07-01 10:00",
        ReturnDate: "2023-07-08 18:00",
        Description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae tincidunt ultricies, nunc nisl ultricies nunc, vitae ultricies Nunc euismod.",
        Price: 1500,
        Capacity: 40,
        Image: "https://cdn.britannica.com/39/6839-050-27891400/Brandenburg-Gate-Berlin.jpg?w=300",
        TourLeaderIds: [2, 3],
        PlaceIds: [16, 17, 18, 19],
    },
    {
        id: 4,
        OraganizationId: 3,
        Origin: { country: "Japan", city: "Tokyo" },
        Destinations: [
            { country: "South Korea", city: "Seoul" },
            { country: "China", city: "Beijing" },
            { country: "Taiwan", city: "Taipei" },
            { country: "Hong Kong", city: "Hong Kong" },
        ],
        DepartureTransportation: "Air Plane",
        ReturnTransportation: "Air Plane",
        DepartureDate: "2023-08-01 14:00",
        ReturnDate: "2023-08-08 22:00",
        Description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl vitae tincidunt ultricies, nunc nisl ultricies nunc, vitae ultricies Nunc euismod.",
        Price: 2500,
        Capacity: 30,
        Image: "",
        TourLeaderIds: [9],
        PlaceIds: [20, 21],
    },
    {
        id: 5,
        OraganizationId: 2,
        Origin: { country: "United States", city: "New York" },
        Destinations: [
            { country: "Canada", city: "Toronto" },
            { country: "Mexico", city: "Cancun" },
            { country: "Brazil", city: "Rio de Janeiro" },
        ],
        DepartureTransportation: "Air Plane",
        ReturnTransportation: "Cruise",
        DepartureDate: "2023-06-01 20:00",
        ReturnDate: "2023-06-15 08:00",
        Description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, enim vel bibendum luctus, velit sapien ultrices sapien, vel tincidunt quam velit vel nunc. Sed euismod, enim vel bibendum luctus, velit sapien ultrices sapien.",
        Price: 2000,
        Capacity: 20,
        Image: "https://picsum.photos/200/300",
        TourLeaderIds: [4, 5],
        PlaceIds: [1, 2],
    },
    {
        id: 6,
        OraganizationId: 3,
        Origin: { country: "United States", city: "Los Angeles" },
        Destinations: [
            { country: "Canada", city: "Vancouver" },
            { country: "Mexico", city: "Cancun" },
            { country: "Brazil", city: "Sao Paulo" },
        ],
        DepartureTransportation: "Air Plane",
        ReturnTransportation: "Cruise",
        DepartureDate: "2023-07-01",
        ReturnDate: "",
        Description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, enim vel bibendum luctus, velit sapien ultrices sapien.",
        Price: 1000,
        Capacity: 30,
        Image: "https://picsum.photos/200/300",
        TourLeaderIds: [3],
        PlaceIds: [3],
    },
    {
        id: 7,
        OraganizationId: 1,
        Origin: { country: "France", city: "Monaco" },
        Destinations: [
            { country: "Iran", city: "Tehran" },
            { country: "Iraq", city: "Baghdad" },
        ],
        DepartureTransportation: "Bus",
        ReturnTransportation: "Air Plane",
        DepartureDate: "2023-08-01 07:00",
        ReturnDate: "2023-08-05 23:30",
        Description:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, enim vel bibendum luctus.",
        Price: 5000,
        Capacity: 50,
        Image: "https://picsum.photos/200/300",
        TourLeaderIds: [4],
        PlaceIds: [4],
    },
];

export default Trips;
